apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: tashan_weir
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      timescaledb: true
    editable: true
